{{- if .Values.egressGateway.enabled }}
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: {{ include "cluster-detector.fullname" . }}-detector-dr
spec:
  host: {{ .Values.detector.host | quote }}
  trafficPolicy:
    tls:
      mode: SIMPLE
{{- end }}
