apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: mesh-demo-gateway
  namespace: mesh-demo
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - mesh-demo.fmt.com.tw
