{{- if .Values.ingressGateway.enabled }}
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: {{ include "cluster-detector.fullname" . }}-gw
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    istio: {{ .Values.ingressGateway.name }}
  servers:
    - port:
        number: {{ .Values.ingressGateway.port }}
        name: http
        protocol: HTTP
      hosts:
        {{- range .Values.ingressGateway.hosts }}
        - {{ . | quote }}
        {{- end }}
{{- end }}
