apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ .Values.service.name }}
spec:
  hosts:
    - {{ .Values.virtualService.host | quote }}
  http:
    - route:
        - destination:
            host: {{ .Values.virtualService.host | quote }}
            subset: v1
          weight: {{ .Values.traffic.v1 }}
        - destination:
            host: {{ .Values.virtualService.host | quote }}
            subset: v2
          weight: {{ .Values.traffic.v2 }}