clusterId: "gke-sit-a"

image:
  repository: nginx
  tag: "1.27-alpine"
  pullPolicy: IfNotPresent

service:
  name: web
  port: 80

# v1/v2 副本數
replicaCount:
  v1: 2
  v2: 2

# 灰度比例（VirtualService weights）
traffic:
  v1: 80
  v2: 20

# 若 namespace 不是 default，請於安裝時用 -n 指定；此處 hosts 用 FQDN 形式
virtualService:
  host: "web.mesh-demo.svc.cluster.local"

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}